load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "poly",
    srcs = [
        "__init__.py",
        "eq.py",
        "geq.py",
        "multilinear.py",
        "univariate.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/utils:bits",
        "//zorch/utils:field",
        requirement("jax"),
        requirement("zk_dtypes"),
    ],
)
