load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "reed_solomon",
    srcs = [
        "__init__.py",
        "reed_solomon.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/poly",
        "//zorch/utils:bits",
        "//zorch/utils:field",
        requirement("jax"),
        requirement("zk_dtypes"),
    ],
)

py_library(
    name = "linear_code",
    srcs = ["linear_code.py"],
    visibility = ["//visibility:public"],
    deps = [
        requirement("jax"),
    ],
)

py_library(
    name = "foldable_code",
    srcs = ["foldable_code.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":linear_code",
        requirement("jax"),
    ],
)

py_library(
    name = "tensor_code",
    srcs = ["tensor_code.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":linear_code",
        requirement("jax"),
    ],
)
