load("@rules_python//python:defs.bzl", "py_test")
load("@zorch_pip//:requirements.bzl", "requirement")
load("//:defs.bzl", "GPU_PLUGIN_DEPS")

py_test(
    name = "random_field_test",
    size = "small",
    srcs = ["random_field_test.py"],
    deps = [
        "//zorch/testkit:random_field",
        requirement("absl_py"),
        requirement("frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "fusion_test",
    size = "medium",
    srcs = ["fusion_test.py"],
    deps = [
        "//zorch/testkit:fusion",
        "//zorch/testkit:koalabear16",
        requirement("absl_py"),
        requirement("frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "transcript_test",
    size = "small",
    srcs = ["transcript_test.py"],
    deps = [
        "//zorch:transcript",
        "//zorch/testkit:transcript",
        requirement("absl_py"),
        requirement("frx"),
        requirement("hash_frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "koalabear16_test",
    size = "small",
    srcs = ["koalabear16_test.py"],
    deps = [
        "//zorch/testkit:koalabear16",
        requirement("absl_py"),
        requirement("frx"),
        requirement("numpy"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)
