load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "whir",
    srcs = [
        "__init__.py",
        "_math.py",
        "config.py",
        "prover.py",
        "scheme.py",
        "verifier.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:stage",
        "//zorch:transcript",
        "//zorch/coding:reed_solomon",
        "//zorch/commit:merkle",
        "//zorch/commit:strided_merkle",
        "//zorch/pcs:fold",
        "//zorch/pcs:stage",
        "//zorch/poly",
        "//zorch/sumcheck",
        "//zorch/utils:bits",
        requirement("frx"),
    ],
)
