load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "poseidon",
    srcs = [
        "__init__.py",
        "linear.py",
        "params.py",
        "poseidon.py",
        "sparse.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:fusion",
        "//zorch/hash:linear",
        "//zorch/hash:permutation",
        "//zorch/hash:sponge",
        requirement("frx"),
        requirement("numpy"),
    ],
)
