load("@rules_python//python:defs.bzl", "py_test")
load("@zorch_pip//:requirements.bzl", "requirement")
load("//:defs.bzl", "GPU_PLUGIN_DEPS")

py_test(
    name = "geq_test",
    size = "small",
    srcs = ["geq_test.py"],
    deps = [
        "//zorch/poly",
        "//zorch/testkit:random_field",
        requirement("absl_py"),
        requirement("frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "eq_test",
    size = "medium",
    srcs = ["eq_test.py"],
    deps = [
        "//zorch/poly",
        requirement("absl_py"),
        requirement("frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "univariate_test",
    size = "small",
    srcs = ["univariate_test.py"],
    deps = [
        "//zorch/poly",
        "//zorch/testkit:random_field",
        requirement("absl_py"),
        requirement("frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "multilinear_test",
    size = "small",
    srcs = ["multilinear_test.py"],
    deps = [
        "//zorch/poly",
        requirement("absl_py"),
        requirement("frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)
