load("@rules_python//python:defs.bzl", "py_test")
load("@zorch_pip//:requirements.bzl", "requirement")
load("//:defs.bzl", "GPU_PLUGIN_DEPS")

py_test(
    name = "eq_poly_test",
    size = "small",
    srcs = ["eq_poly_test.py"],
    deps = [
        "//zorch:transcript",
        "//zorch/poly",
        "//zorch/sumcheck",
        "//zorch/sumcheck/eq",
        "//zorch/testkit:transcript",
        requirement("absl_py"),
        requirement("jax"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "small_value_test",
    size = "small",
    srcs = ["small_value_test.py"],
    deps = [
        "//zorch/sumcheck/eq",
        "//zorch/testkit:transcript",
        requirement("absl_py"),
        requirement("jax"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)
