load("@rules_python//python:defs.bzl", "py_test")
load("@zorch_pip//:requirements.bzl", "requirement")
load("//:defs.bzl", "GPU_PLUGIN_DEPS")

py_test(
    name = "_composite_test",
    size = "small",
    srcs = ["_composite_test.py"],
    deps = [
        "//zorch:_composite",
        requirement("absl_py"),
        requirement("jax"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "fusion_test",
    size = "small",
    srcs = ["fusion_test.py"],
    deps = [
        "//zorch:_composite",
        "//zorch:fusion",
        "//zorch/testkit:random_field",
        requirement("absl_py"),
        requirement("jax"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "constraint_eval_test",
    size = "small",
    srcs = ["constraint_eval_test.py"],
    deps = [
        "//zorch:_composite",
        "//zorch:constraint_eval",
        "//zorch/testkit:random_field",
        requirement("absl_py"),
        requirement("jax"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "prove_test",
    size = "small",
    srcs = ["prove_test.py"],
    deps = [
        "//zorch:prove",
        "//zorch:round",
        "//zorch/testkit:transcript",
        requirement("absl_py"),
        requirement("jax"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "round_test",
    size = "small",
    srcs = ["round_test.py"],
    deps = [
        "//zorch:round",
        "//zorch:transcript",
        "//zorch/testkit:transcript",
        requirement("absl_py"),
        requirement("jax"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "scan_test",
    size = "small",
    srcs = ["scan_test.py"],
    deps = [
        "//zorch:verify",
        "//zorch/sumcheck",
        "//zorch/testkit:transcript",
        requirement("absl_py"),
        requirement("jax"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "transcript_test",
    size = "small",
    srcs = ["transcript_test.py"],
    deps = [
        "//zorch:transcript",
        "//zorch/hash/poseidon2/testing:koalabear16",
        "//zorch/testkit:jit_cache",
        "//zorch/testkit:random_field",
        "//zorch/testkit:transcript",
        requirement("absl_py"),
        requirement("jax"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)
