load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "merkle",
    srcs = [
        "__init__.py",
        "merkle.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:fusion",
        "//zorch/hash:compression",
        "//zorch/hash:sponge",
        "//zorch/utils:bits",
        requirement("frx"),
    ],
)

py_library(
    name = "strided_merkle",
    srcs = ["strided_merkle.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":merkle",
        "//zorch:fusion",
        "//zorch/hash:compression",
        "//zorch/hash:sponge",
        "//zorch/utils:bits",
        requirement("frx"),
    ],
)

py_library(
    name = "smcs",
    srcs = ["smcs.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/commit:merkle",
        "//zorch/hash:compression",
        "//zorch/hash:sponge",
        "//zorch/utils:bits",
        requirement("frx"),
        requirement("zk_dtypes"),
    ],
)
