load("@rules_python//python:defs.bzl", "py_binary", "py_library", "py_test")
load("@zorch_pip//:requirements.bzl", "requirement")

py_binary(
    name = "bench_merkle_commit",
    srcs = ["bench_merkle_commit.py"],
    deps = [
        "//zorch/commit/testing:koalabear16",
        requirement("jax"),
        requirement("jax_cuda12_plugin"),
        requirement("zk_dtypes"),
        requirement("zkbench"),
        requirement("zkx_cuda_pjrt"),
    ],
)

py_library(
    name = "merkle",
    srcs = [
        "__init__.py",
        "merkle.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/hash:compression",
        "//zorch/hash:sponge",
        "//zorch/utils:bits",
        requirement("jax"),
    ],
)

py_test(
    name = "merkle_test",
    size = "small",
    srcs = ["merkle_test.py"],
    env = {"JAX_PLATFORMS": "cpu"},
    deps = [
        ":merkle",
        "//zorch/commit/testing:koalabear16",
        "//zorch/hash:compression",
        "//zorch/hash:sponge",
        "//zorch/hash/poseidon2/testing:koalabear16",
        requirement("jax"),
        requirement("zk_dtypes"),
    ],
)
