load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "random_field",
    srcs = [
        "__init__.py",
        "random_field.py",
    ],
    visibility = ["//zorch:__subpackages__"],
    deps = [
        requirement("jax"),
        requirement("numpy"),
    ],
)

py_library(
    name = "fusion",
    srcs = ["fusion.py"],
    visibility = ["//zorch:__subpackages__"],
    deps = [requirement("jax")],
)
