load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "poly",
    srcs = [
        "__init__.py",
        "branching_program.py",
        "poly.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":dense",
        "//zorch:fusion",
        "//zorch/poly",
        "//zorch/utils:bits",
        requirement("frx"),
        requirement("numpy"),
    ],
)

py_library(
    name = "dense",
    srcs = ["dense.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/utils:bits",
    ],
)

py_library(
    name = "region",
    srcs = ["region.py"],
    visibility = ["//visibility:public"],
    deps = [
        requirement("frx"),
    ],
)

py_library(
    name = "commit",
    srcs = ["commit.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":region",
        "//zorch/coding:reed_solomon",
        "//zorch/commit:smcs",
        requirement("frx"),
    ],
)

py_library(
    name = "prover",
    srcs = ["prover.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:round",
        "//zorch:transcript",
        "//zorch/pcs/jagged:poly",
        "//zorch/poly",
        "//zorch/utils:bits",
        requirement("frx"),
        requirement("numpy"),
        requirement("zk_dtypes"),
    ],
)

py_library(
    name = "open",
    srcs = ["open.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:transcript",
        "//zorch/coding:reed_solomon",
        "//zorch/commit:smcs",
        "//zorch/pcs/basefold",
        "//zorch/poly",
        "//zorch/utils:bits",
        requirement("frx"),
        requirement("zk_dtypes"),
    ],
)

py_library(
    name = "verifier",
    srcs = ["verifier.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:challenge",
        "//zorch:transcript",
        "//zorch:verify",
        "//zorch/coding:reed_solomon",
        "//zorch/commit:merkle",
        "//zorch/commit:smcs",
        "//zorch/pcs:fold",
        "//zorch/pcs/basefold",
        "//zorch/pcs/jagged:open",
        "//zorch/pcs/jagged:poly",
        "//zorch/pcs/jagged:prover",
        "//zorch/poly",
        "//zorch/sumcheck",
        "//zorch/utils:bits",
        requirement("frx"),
        requirement("zk_dtypes"),
    ],
)
