load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "poly",
    srcs = [
        "__init__.py",
        "poly.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/poly",
        "//zorch/utils:bits",
        requirement("jax"),
        requirement("numpy"),
    ],
)

py_library(
    name = "dense",
    srcs = ["dense.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/utils:bits",
        requirement("jax"),
    ],
)

py_library(
    name = "inner_sumcheck",
    srcs = ["inner_sumcheck.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:prove",
        "//zorch:round",
        "//zorch:transcript",
        "//zorch/pcs/jagged:poly",
        "//zorch/poly",
        requirement("jax"),
        requirement("zk_dtypes"),
    ],
)

py_library(
    name = "stacked",
    srcs = ["stacked.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/pcs/basefold:prover",
        "//zorch/pcs/basefold:verifier",
        "//zorch/pcs/jagged:dense",
        "//zorch/poly",
        requirement("jax"),
    ],
)
