load("@rules_python//python:defs.bzl", "py_library", "py_test")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "permutation",
    srcs = [
        "__init__.py",
        "permutation.py",
    ],
    visibility = ["//visibility:public"],
    deps = [requirement("jax")],
)

py_test(
    name = "permutation_test",
    size = "small",
    srcs = ["permutation_test.py"],
    env = {"JAX_PLATFORMS": "cpu"},
    deps = [
        ":permutation",
        requirement("jax"),
    ],
)

py_library(
    name = "compression",
    srcs = ["compression.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":permutation",
        requirement("jax"),
    ],
)

py_test(
    name = "compression_test",
    size = "small",
    srcs = ["compression_test.py"],
    env = {"JAX_PLATFORMS": "cpu"},
    deps = [
        ":compression",
        "//zorch/hash/poseidon2/testing:koalabear16",
        requirement("jax"),
        requirement("zk_dtypes"),
    ],
)

py_library(
    name = "sponge",
    srcs = ["sponge.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":permutation",
        requirement("jax"),
    ],
)

py_test(
    name = "sponge_test",
    size = "small",
    srcs = ["sponge_test.py"],
    env = {"JAX_PLATFORMS": "cpu"},
    deps = [
        ":sponge",
        "//zorch/hash/poseidon2/testing:koalabear16",
        requirement("jax"),
        requirement("zk_dtypes"),
    ],
)
