load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "fold",
    srcs = ["fold.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:round",
        "//zorch:transcript",
        "//zorch/coding:foldable_code",
        "//zorch/commit:merkle",
        requirement("jax"),
    ],
)

py_library(
    name = "matrix_commit",
    srcs = ["matrix_commit.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/coding:linear_code",
        "//zorch/commit:merkle",
        "//zorch/pcs:fold",
        requirement("jax"),
    ],
)

py_library(
    name = "protocol",
    srcs = [
        "__init__.py",
        "protocol.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:transcript",
        requirement("jax"),
    ],
)
