load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "deep",
    srcs = ["deep.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/poly",
        requirement("frx"),
    ],
)

py_library(
    name = "fold",
    srcs = ["fold.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch:round",
        "//zorch:transcript",
        "//zorch/coding:foldable_code",
        "//zorch/commit:merkle",
        requirement("frx"),
    ],
)

py_library(
    name = "matrix_commit",
    srcs = ["matrix_commit.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/coding:linear_code",
        "//zorch/commit:merkle",
        "//zorch/pcs:fold",
        requirement("frx"),
    ],
)

py_library(
    name = "stage",
    srcs = [
        "__init__.py",
        "stage.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        requirement("frx"),
    ],
)

py_library(
    name = "ring_switch",
    srcs = ["ring_switch.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//zorch/utils:binary_field",
        requirement("frx"),
    ],
)
