load("@rules_python//python:defs.bzl", "py_library")
load("@zorch_pip//:requirements.bzl", "requirement")

py_library(
    name = "bits",
    srcs = [
        "__init__.py",
        "bits.py",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "field",
    srcs = [
        "__init__.py",
        "field.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        requirement("jax"),
        requirement("zk_dtypes"),
    ],
)
