load("@rules_python//python:defs.bzl", "py_library", "py_test")
load("@zorch_pip//:requirements.bzl", "requirement")
load("//:defs.bzl", "GPU_PLUGIN_DEPS")

py_library(
    name = "koalabear16",
    srcs = [
        "__init__.py",
        "koalabear16.py",
    ],
    visibility = ["//zorch:__subpackages__"],
    deps = [
        "//zorch/hash/poseidon2",
        requirement("frx"),
        requirement("numpy"),
        requirement("zk_dtypes"),
    ],
)

py_test(
    name = "poseidon2_test",
    size = "medium",
    srcs = ["poseidon2_test.py"],
    deps = [
        ":koalabear16",
        "//zorch:_composite",
        "//zorch/testkit:jit_cache",
        requirement("absl_py"),
        requirement("frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "params_test",
    size = "small",
    srcs = ["params_test.py"],
    deps = [
        "//zorch/hash/poseidon2",
        requirement("absl_py"),
        requirement("frx"),
        requirement("numpy"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "permute_shape_test",
    size = "medium",
    srcs = ["permute_shape_test.py"],
    deps = [
        "//zorch/hash/poseidon2",
        requirement("absl_py"),
        requirement("frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)

py_test(
    name = "linear_test",
    size = "small",
    srcs = ["linear_test.py"],
    deps = [
        "//zorch/hash/poseidon2",
        "//zorch/testkit:fusion",
        "//zorch/testkit:random_field",
        requirement("absl_py"),
        requirement("frx"),
        requirement("zk_dtypes"),
    ] + GPU_PLUGIN_DEPS,
)
